### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by nconrad** [nconrad/mauve_viewer#2]
- [x] display 'N/A' for unavailable feature info
- [x] body container for tooltip position (make optional)
- [x] fix show/hide genome id bug
- [x] title tags
- [x] close "options" on selection
